In [2]:
import pandas as pd
import numpy as np
import scipy.linalg as la
url='http://wolfpack.hnu.ac.kr/Stat_Notes/adv_stat/LinearModel/data/SMSA.csv'
smsa=pd.read_csv(url)
y=np.asarray(smsa.loc[:,'Mortality'])
x=np.asarray(smsa.iloc[:,[6,8]])
one=np.array(np.repeat(1,y.size))
X=np.column_stack((one,x))
la.inv(X.T@X)@X.T@y

array([1212.00053826,  -28.99139329,    3.91578355])

In [3]:
import pandas as pd
import numpy as np
import scipy.linalg as la
url='http://wolfpack.hnu.ac.kr/Stat_Notes/adv_stat/LinearModel/data/SMSA.csv'
smsa=pd.read_csv(url)
y=np.asarray(smsa.loc[:,'Mortality'])
x=np.asarray(smsa.iloc[:,[6,8]])
one=np.array(np.repeat(1,y.size))
X=np.column_stack((one,x))
la.inv(X.T@X)@X.T@y

array([1212.00053826,  -28.99139329,    3.91578355])

In [4]:
import pandas as pd
import numpy as np
import scipy.linalg as la
url='http://wolfpack.hnu.ac.kr/Stat_Notes/adv_stat/LinearModel/data/SMSA.csv'
smsa=pd.read_csv(url)
y=np.asarray(smsa.loc[:,'Mortality'])
x=np.asarray[smsa.iloc[:,[6,8]]]
one=np.array[np.repeat(1,y.size)]
X=np.column_stack((one,x))
la.inv(X.T@X)@X.T@y

In [6]:
list(smsa)

['city',
 'Mortality',
 'JanTemp',
 'JulyTemp',
 'RelHum',
 'Rain',
 'Education',
 'PopDensity',
 'NonWhite',
 'WC',
 'pop/house',
 'income',
 'HCPot',
 'NOxPot',
 'S02Pot']

In [10]:
x2=np.asarray(smsa.iloc[:,[3,4]])
X2=np.column_stack((one,x2))
la.inv(X2.T@X2)@X2.T@y

array([6.18207151e+02, 3.89847048e+00, 5.44172118e-01])